### PR TITLE
Implementing Styled Components

### PR DESCRIPTION
**Pull request by CFIALeronB**
Implementing Styled Components and removing unused CSS objects.

#7

### CODE REVIEW

**Review by rngadam — APPROVED** [review]
LGTM

**Comment by rngadam** [comment]
@S-Khos please review

**Review by S-Khos — APPROVED** [review]

**Comment by CFIALeronB** [comment]
Old PR, created a new one

**Comment by rngadam** [comment]
@CFIALeronB ok, then can you close this one?

**Pull request closed without merging**
