### PR TITLE
Issue77-migrate-to-vite

### LINKED ISSUE #77: Migrate finesse-frontend from Create-React-App
We currently have finesse-frontend built using `create-react-app` which is now deprecated. As a consequence, vulnerabilities are piling up in the package management. We decided to migrate to `Vite`.

## Tasks
- [ ] Recreate the project with Vite.
- [ ] Update the project's package.json scripts to use Vite commands for development and building.
- [ ] Test the project thoroughly to ensure that it functions correctly after the migration.
- [ ] Update dependencies.
- [ ] Update the project documentation.

Acceptance Criteria:
- finesse-frontend successfully builds and runs using Vite without errors.
- All existing features and functionalities work as expected.
- The project's documentation is updated to include instructions for running and developing the project with Vite.

### PR DESCRIPTION
**Pull request by k-allagbe**
Closes #77: Migrate from CRA to Vite

- [x] migration
- [x] update tests
- [x] update doc
- [x] update version

### CODE REVIEW

**Comment by k-allagbe** [comment]
@ThomasCardin I may have broken the lint-test workflow for this repo. Please could you take a look. I opened this https://github.com/ai-cfia/github-workflows/issues/85 which might fix it.
Please, note that:
- the npm version 9 is no longer required
- the env vars have changed. The required `REACT_APP_` prefix is now `VITE_`.

**Review by rngadam — CHANGES_REQUESTED** [review]
Ensure that @CFIALeronB has reviewed this change

**Review by rngadam — APPROVED** [review]

**Review by CFIALeronB — APPROVED** [review]
Everything seems to be in working well using vite

**Comment by k-allagbe** [comment]
@ThomasCardin please could you look at these:
https://github.com/ai-cfia/finesse-frontend/actions/runs/7826419055/job/21352248544?pr=81
https://github.com/ai-cfia/finesse-frontend/actions/runs/7826419055/job/21352248544?pr=81

I have no clue what's happening.

**Pull request merged**
